### ISSUE TITLE
NanoPi_NEO_Core support

### ISSUE THREAD

**Issue by kroko** [Tungsteno74/NPi.GPIO#39]
Why there's [exlicity](https://github.com/Tungsteno74/NPi.GPIO/blob/release/source/py_gpio.c#L676) no _NanoPi NEO Core_ support? 

It presumably is the same as NanoPi NEO & AIR, simply [with bare headers](http://linux-sunxi.org/FriendlyARM_NanoPi_NEO_%26_AIR#NanoPi_NEO_Core)

> In the NEO Core variant, the ethernet and USB A connectors are replaced with unpopulated headers. 

And from [FriendlyARM own description](http://wiki.friendlyarm.com/wiki/index.php/NanoPi_NEO_Core#Introduction):

> It has the same form factor as the NanoPi NEO and same pin descriptions.

```sh
root@NanoPi-NEO-Core:~# uname -a
Linux NanoPi-NEO-Core 4.14.111 #64 SMP Mon May 20 15:32:02 CST 2019 armv7l armv7l armv7l GNU/Linux
```

Thanks!

**Comment by kroko** [comment]
Just did a quick test

_source/boardtype_friendlyelec.c_

```c
int getBoardType(BoardHardwareInfo** retBoardInfo)
{
// Force use NanoPi_NEO (just fake index 23 from BoardHardwareInfo array, NanoPi_NEO_Core index is 27)
    int hackIdx = 23;
    *retBoardInfo = &gAllBoardHardwareInfo[hackIdx];
    return gAllBoardHardwareInfo[hackIdx].boardTypeId;
// returns here

}
```

It launches. But yeah... not the same routing.  
I have some buttons attached on external interrupts on pins 11, 12, 13, 15. None, except for one, responded.
Pin 12 in `NanoPi_NEO` definitions is actually pin 12 on `NanoPi_NEO_Core`. And using `GPIO.input()` within the callback did not work.

**Comment by kroko** [comment]
Or maybe not.


NanoPi_NEO layout
http://wiki.friendlyarm.com/wiki/index.php/NanoPi_NEO#Layout
http://wiki.friendlyarm.com/wiki/images/5/51/Schematic_NanoPi-NEO-V1_4-1801-20180320.pdf

NanoPi_NEO_Core layout
http://wiki.friendlyarm.com/wiki/index.php/NanoPi_NEO_Core#Layout
http://wiki.friendlyarm.com/wiki/images/a/a4/Nanopi_neo_core-v1.1-1802.pdf

In PDFs `CON1` on `NanoPi_NEO` (Sheet 11/12) and `J1` on `NanoPi_NEO_Core` (Sheet 11/11) **are the same**. And I'm using pins
* 11 (D11, PA0/UART2_TX/JTAG_MS0/PA_EINT0)
* 12 (E14, PA6/SIM_PWREN/PWM1/PA_EINT6)
* 13 (D6, PA2/UART2_RTS/JTAG_DO0/PA_EINT2)
* 15 (E13, PA3/UART2_CTS/JTAG_DI0/PA_EINT3)
which map to same mCU pins on both boards (`U1D` on Sheet 5 in both cases). Thus my wild guess is that actually `NanoPi_NEO` mapping in this lib is wrong, not that it cannot be applied to `NanoPi_NEO_Core` (?).

**Comment by Tungsteno74** [comment]
Hello @kroko,
sorry for my late delay. 
I haven't a CORE version of NanoPi NEO so i can't test or try to fix any issue on it. I've tested the pins state only on Neo v1.3 (this is the only board that i have) and all seem to work well, so i don't think is a lib issue. Most likely there is a different pin configuration even if it is not mentioned in the official datasheet.
In any case, since I didn't actually write the C code (i've only fixed some little issues with my board), you could try using the interactive test file **gpio_interactive_test.py** that you find in the test folder and, see which pins don't work and mark them, then you can try to fix the problem yourself. If you can figure out where the issue is, you can create a pull request and i'll be happy to update the package.

Cheers

**Comment by kroko** [comment]
@Tungsteno74 thanks for getting back to me. I solved my issue by using https://github.com/auto3000/RPi.GPIO_NP - using that fork external interrupts work OOB using both vendor's supplied distro as well as Armbian (went with the latter). It is really a one-off project, thus I'm not looking forward to dig deeper into it, just needed a quick and dirty python solution. Thanks anyways! 😉
