### ISSUE TITLE
Support for NanoPi Duo2

### ISSUE THREAD

**Issue by versamodule** [Tungsteno74/NPi.GPIO#41]
You are the only person I have found that took the time to make this work with Python3.
Unfortunatly, the NanoPi Duo2 was not included. 
If you don't have the time to add it, that is ok, but would you be able to tell me then what files I would need to change and what to add to make that happen. 

Sorry to bother you, but thank you for the time.

**Comment by Tungsteno74** [comment]
Hello @versamodule,
Sorry for the late reply but right now, my main pc is broken and I'm trying to assemble another one.
Now, the main problem is that I don't have that board but only a NanoPi Neo, so I can't test any code. This is why I prefer not to add any more potentially problematic code to this library.
However, if you have the card in question and are able to modify the necessary code, it would be fantastic. In this case, I could give you some suggestions (but don't expect much by the way, since each board has a different behavior). In addition, in this period, I have other things to do for work and they don't allow me to follow this project anymore.

In any case, if you want to implement some support for this card, what you need is board **pin mapping** (try looking for it on Google).
`Source` is the main project folder. Inside it there are files written in C which determine the behavior of the library. The two main files related to **pin mapping** are `boardtype_friendlyelec.c` and `boardtype_friendlyelec.h`.

Have fun :)

**Comment by Tungsteno74** [comment]
@versamodule  Hello. Do you have solved it?

**Comment by versamodule** [comment]
No, I have moved on to a different device.
